POST {{url}}/pay-by-square-generator/generate-qr
Content-Type: application/json

{
  "amount": 20.00,
  "iban": "SK7311000000002610305468",
  "swift": "FIOZSKBAXXX",
  "currency": "EUR",
  "variableSymbol": "123456",
  "constantSymbol": "0308",
  "specificSymbol": "789",
  "note": "Platba za fakturu",
  "beneficiaryName": "Tester Testovič",
  "beneficiaryAddress1": "Hlavna 1",
  "beneficiaryAddress2": "Bratislava",
  "date": "2025-10-21"
}

>> out/qr-code.png

###
POST {{url}}/pay-by-square-generator/generate-qr
Content-Type: application/json

{
  "amount": 20.00,
  "iban": "SK7311000000002610305468",
  "currency": "EUR",
  "variableSymbol": "123456",
  "note": "Platba za fakturu",
  "beneficiaryName": "Tester Testovič",
  "date": "2025-10-21"
}

>> out/qr-code.png

###
GET http://localhost:3000/pay-by-square-generator/version.txt